var masterData = [
  {
  "login": "lapty",
  "id": 8241367,
  "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
  "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
  "url": "https://api.github.com/users/lapty",
  "html_url": "https://github.com/lapty",
  "followers_url": "https://api.github.com/users/lapty/followers",
  "following_url": "https://api.github.com/users/lapty/following{/other_user}",
  "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
  "organizations_url": "https://api.github.com/users/lapty/orgs",
  "repos_url": "https://api.github.com/users/lapty/repos",
  "events_url": "https://api.github.com/users/lapty/events{/privacy}",
  "received_events_url": "https://api.github.com/users/lapty/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Charles Nguyen",
  "company": "",
  "blog": "",
  "location": "Charleston, SC",
  "email": "charles.qh.nguyen@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 13,
  "public_gists": 0,
  "followers": 12,
  "following": 17,
  "created_at": "2014-07-23T02:31:13Z",
  "updated_at": "2014-08-06T23:12:18Z"
} ]


var repoList = [
  {
    "id": 22455349,
    "name": "basicJavascript",
    "full_name": "lapty/basicJavascript",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/basicJavascript",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/basicJavascript",
    "forks_url": "https://api.github.com/repos/lapty/basicJavascript/forks",
    "keys_url": "https://api.github.com/repos/lapty/basicJavascript/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/basicJavascript/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/basicJavascript/teams",
    "hooks_url": "https://api.github.com/repos/lapty/basicJavascript/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/basicJavascript/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/basicJavascript/events",
    "assignees_url": "https://api.github.com/repos/lapty/basicJavascript/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/basicJavascript/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/basicJavascript/tags",
    "blobs_url": "https://api.github.com/repos/lapty/basicJavascript/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/basicJavascript/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/basicJavascript/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/basicJavascript/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/basicJavascript/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/basicJavascript/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/basicJavascript/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/basicJavascript/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/basicJavascript/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/basicJavascript/subscription",
    "commits_url": "https://api.github.com/repos/lapty/basicJavascript/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/basicJavascript/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/basicJavascript/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/basicJavascript/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/basicJavascript/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/basicJavascript/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/basicJavascript/merges",
    "archive_url": "https://api.github.com/repos/lapty/basicJavascript/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/basicJavascript/downloads",
    "issues_url": "https://api.github.com/repos/lapty/basicJavascript/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/basicJavascript/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/basicJavascript/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/basicJavascript/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/basicJavascript/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/basicJavascript/releases{/id}",
    "created_at": "2014-07-31T03:44:08Z",
    "updated_at": "2014-08-03T03:18:31Z",
    "pushed_at": "2014-07-31T04:13:52Z",
    "git_url": "git://github.com/lapty/basicJavascript.git",
    "ssh_url": "git@github.com:lapty/basicJavascript.git",
    "clone_url": "https://github.com/lapty/basicJavascript.git",
    "svn_url": "https://github.com/lapty/basicJavascript",
    "homepage": null,
    "size": 108,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22312443,
    "name": "climbOn",
    "full_name": "lapty/climbOn",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/climbOn",
    "description": "Playing with layout + design",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/climbOn",
    "forks_url": "https://api.github.com/repos/lapty/climbOn/forks",
    "keys_url": "https://api.github.com/repos/lapty/climbOn/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/climbOn/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/climbOn/teams",
    "hooks_url": "https://api.github.com/repos/lapty/climbOn/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/climbOn/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/climbOn/events",
    "assignees_url": "https://api.github.com/repos/lapty/climbOn/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/climbOn/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/climbOn/tags",
    "blobs_url": "https://api.github.com/repos/lapty/climbOn/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/climbOn/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/climbOn/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/climbOn/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/climbOn/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/climbOn/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/climbOn/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/climbOn/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/climbOn/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/climbOn/subscription",
    "commits_url": "https://api.github.com/repos/lapty/climbOn/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/climbOn/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/climbOn/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/climbOn/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/climbOn/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/climbOn/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/climbOn/merges",
    "archive_url": "https://api.github.com/repos/lapty/climbOn/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/climbOn/downloads",
    "issues_url": "https://api.github.com/repos/lapty/climbOn/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/climbOn/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/climbOn/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/climbOn/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/climbOn/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/climbOn/releases{/id}",
    "created_at": "2014-07-27T14:14:49Z",
    "updated_at": "2014-08-04T03:45:05Z",
    "pushed_at": "2014-07-27T14:17:31Z",
    "git_url": "git://github.com/lapty/climbOn.git",
    "ssh_url": "git@github.com:lapty/climbOn.git",
    "clone_url": "https://github.com/lapty/climbOn.git",
    "svn_url": "https://github.com/lapty/climbOn",
    "homepage": "",
    "size": 1664,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22682700,
    "name": "constructorProject",
    "full_name": "lapty/constructorProject",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/constructorProject",
    "description": "playing with constructors",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/constructorProject",
    "forks_url": "https://api.github.com/repos/lapty/constructorProject/forks",
    "keys_url": "https://api.github.com/repos/lapty/constructorProject/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/constructorProject/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/constructorProject/teams",
    "hooks_url": "https://api.github.com/repos/lapty/constructorProject/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/constructorProject/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/constructorProject/events",
    "assignees_url": "https://api.github.com/repos/lapty/constructorProject/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/constructorProject/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/constructorProject/tags",
    "blobs_url": "https://api.github.com/repos/lapty/constructorProject/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/constructorProject/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/constructorProject/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/constructorProject/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/constructorProject/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/constructorProject/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/constructorProject/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/constructorProject/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/constructorProject/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/constructorProject/subscription",
    "commits_url": "https://api.github.com/repos/lapty/constructorProject/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/constructorProject/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/constructorProject/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/constructorProject/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/constructorProject/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/constructorProject/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/constructorProject/merges",
    "archive_url": "https://api.github.com/repos/lapty/constructorProject/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/constructorProject/downloads",
    "issues_url": "https://api.github.com/repos/lapty/constructorProject/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/constructorProject/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/constructorProject/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/constructorProject/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/constructorProject/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/constructorProject/releases{/id}",
    "created_at": "2014-08-06T13:02:32Z",
    "updated_at": "2014-08-06T13:03:55Z",
    "pushed_at": "2014-08-06T13:03:55Z",
    "git_url": "git://github.com/lapty/constructorProject.git",
    "ssh_url": "git@github.com:lapty/constructorProject.git",
    "clone_url": "https://github.com/lapty/constructorProject.git",
    "svn_url": "https://github.com/lapty/constructorProject",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22157294,
    "name": "FirstProject",
    "full_name": "lapty/FirstProject",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/FirstProject",
    "description": "Project 1 - July 21",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/FirstProject",
    "forks_url": "https://api.github.com/repos/lapty/FirstProject/forks",
    "keys_url": "https://api.github.com/repos/lapty/FirstProject/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/FirstProject/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/FirstProject/teams",
    "hooks_url": "https://api.github.com/repos/lapty/FirstProject/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/FirstProject/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/FirstProject/events",
    "assignees_url": "https://api.github.com/repos/lapty/FirstProject/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/FirstProject/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/FirstProject/tags",
    "blobs_url": "https://api.github.com/repos/lapty/FirstProject/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/FirstProject/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/FirstProject/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/FirstProject/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/FirstProject/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/FirstProject/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/FirstProject/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/FirstProject/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/FirstProject/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/FirstProject/subscription",
    "commits_url": "https://api.github.com/repos/lapty/FirstProject/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/FirstProject/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/FirstProject/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/FirstProject/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/FirstProject/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/FirstProject/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/FirstProject/merges",
    "archive_url": "https://api.github.com/repos/lapty/FirstProject/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/FirstProject/downloads",
    "issues_url": "https://api.github.com/repos/lapty/FirstProject/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/FirstProject/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/FirstProject/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/FirstProject/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/FirstProject/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/FirstProject/releases{/id}",
    "created_at": "2014-07-23T15:34:13Z",
    "updated_at": "2014-07-24T14:56:44Z",
    "pushed_at": "2014-07-23T15:58:51Z",
    "git_url": "git://github.com/lapty/FirstProject.git",
    "ssh_url": "git@github.com:lapty/FirstProject.git",
    "clone_url": "https://github.com/lapty/FirstProject.git",
    "svn_url": "https://github.com/lapty/FirstProject",
    "homepage": "",
    "size": 148,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22158263,
    "name": "git-demo",
    "full_name": "lapty/git-demo",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/git-demo",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/git-demo",
    "forks_url": "https://api.github.com/repos/lapty/git-demo/forks",
    "keys_url": "https://api.github.com/repos/lapty/git-demo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/git-demo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/git-demo/teams",
    "hooks_url": "https://api.github.com/repos/lapty/git-demo/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/git-demo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/git-demo/events",
    "assignees_url": "https://api.github.com/repos/lapty/git-demo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/git-demo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/git-demo/tags",
    "blobs_url": "https://api.github.com/repos/lapty/git-demo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/git-demo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/git-demo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/git-demo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/git-demo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/git-demo/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/git-demo/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/git-demo/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/git-demo/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/git-demo/subscription",
    "commits_url": "https://api.github.com/repos/lapty/git-demo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/git-demo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/git-demo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/git-demo/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/git-demo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/git-demo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/git-demo/merges",
    "archive_url": "https://api.github.com/repos/lapty/git-demo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/git-demo/downloads",
    "issues_url": "https://api.github.com/repos/lapty/git-demo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/git-demo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/git-demo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/git-demo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/git-demo/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/git-demo/releases{/id}",
    "created_at": "2014-07-23T15:48:48Z",
    "updated_at": "2014-07-23T15:48:48Z",
    "pushed_at": "2014-07-23T15:49:39Z",
    "git_url": "git://github.com/lapty/git-demo.git",
    "ssh_url": "git@github.com:lapty/git-demo.git",
    "clone_url": "https://github.com/lapty/git-demo.git",
    "svn_url": "https://github.com/lapty/git-demo",
    "homepage": null,
    "size": 112,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22157348,
    "name": "LayoutProject",
    "full_name": "lapty/LayoutProject",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/LayoutProject",
    "description": "Project 2 - Jul 22",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/LayoutProject",
    "forks_url": "https://api.github.com/repos/lapty/LayoutProject/forks",
    "keys_url": "https://api.github.com/repos/lapty/LayoutProject/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/LayoutProject/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/LayoutProject/teams",
    "hooks_url": "https://api.github.com/repos/lapty/LayoutProject/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/LayoutProject/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/LayoutProject/events",
    "assignees_url": "https://api.github.com/repos/lapty/LayoutProject/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/LayoutProject/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/LayoutProject/tags",
    "blobs_url": "https://api.github.com/repos/lapty/LayoutProject/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/LayoutProject/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/LayoutProject/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/LayoutProject/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/LayoutProject/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/LayoutProject/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/LayoutProject/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/LayoutProject/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/LayoutProject/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/LayoutProject/subscription",
    "commits_url": "https://api.github.com/repos/lapty/LayoutProject/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/LayoutProject/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/LayoutProject/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/LayoutProject/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/LayoutProject/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/LayoutProject/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/LayoutProject/merges",
    "archive_url": "https://api.github.com/repos/lapty/LayoutProject/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/LayoutProject/downloads",
    "issues_url": "https://api.github.com/repos/lapty/LayoutProject/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/LayoutProject/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/LayoutProject/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/LayoutProject/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/LayoutProject/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/LayoutProject/releases{/id}",
    "created_at": "2014-07-23T15:34:55Z",
    "updated_at": "2014-07-24T14:56:29Z",
    "pushed_at": "2014-07-23T16:02:06Z",
    "git_url": "git://github.com/lapty/LayoutProject.git",
    "ssh_url": "git@github.com:lapty/LayoutProject.git",
    "clone_url": "https://github.com/lapty/LayoutProject.git",
    "svn_url": "https://github.com/lapty/LayoutProject",
    "homepage": "",
    "size": 776,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22399039,
    "name": "letsEat",
    "full_name": "lapty/letsEat",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/letsEat",
    "description": "layout project, modified for responsive",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/letsEat",
    "forks_url": "https://api.github.com/repos/lapty/letsEat/forks",
    "keys_url": "https://api.github.com/repos/lapty/letsEat/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/letsEat/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/letsEat/teams",
    "hooks_url": "https://api.github.com/repos/lapty/letsEat/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/letsEat/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/letsEat/events",
    "assignees_url": "https://api.github.com/repos/lapty/letsEat/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/letsEat/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/letsEat/tags",
    "blobs_url": "https://api.github.com/repos/lapty/letsEat/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/letsEat/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/letsEat/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/letsEat/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/letsEat/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/letsEat/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/letsEat/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/letsEat/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/letsEat/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/letsEat/subscription",
    "commits_url": "https://api.github.com/repos/lapty/letsEat/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/letsEat/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/letsEat/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/letsEat/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/letsEat/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/letsEat/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/letsEat/merges",
    "archive_url": "https://api.github.com/repos/lapty/letsEat/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/letsEat/downloads",
    "issues_url": "https://api.github.com/repos/lapty/letsEat/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/letsEat/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/letsEat/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/letsEat/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/letsEat/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/letsEat/releases{/id}",
    "created_at": "2014-07-29T23:02:31Z",
    "updated_at": "2014-07-29T23:04:03Z",
    "pushed_at": "2014-07-30T02:44:58Z",
    "git_url": "git://github.com/lapty/letsEat.git",
    "ssh_url": "git@github.com:lapty/letsEat.git",
    "clone_url": "https://github.com/lapty/letsEat.git",
    "svn_url": "https://github.com/lapty/letsEat",
    "homepage": null,
    "size": 784,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22701250,
    "name": "manipulatingDomWithConstructors",
    "full_name": "lapty/manipulatingDomWithConstructors",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/manipulatingDomWithConstructors",
    "description": "Aug 6 Project",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors",
    "forks_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/forks",
    "keys_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/teams",
    "hooks_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/events",
    "assignees_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/tags",
    "blobs_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/subscription",
    "commits_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/merges",
    "archive_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/downloads",
    "issues_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors/releases{/id}",
    "created_at": "2014-08-06T23:11:27Z",
    "updated_at": "2014-08-06T23:12:18Z",
    "pushed_at": "2014-08-06T23:12:18Z",
    "git_url": "git://github.com/lapty/manipulatingDomWithConstructors.git",
    "ssh_url": "git@github.com:lapty/manipulatingDomWithConstructors.git",
    "clone_url": "https://github.com/lapty/manipulatingDomWithConstructors.git",
    "svn_url": "https://github.com/lapty/manipulatingDomWithConstructors",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22565887,
    "name": "photoAlbum",
    "full_name": "lapty/photoAlbum",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/photoAlbum",
    "description": "Basic jQuery photo album project",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/photoAlbum",
    "forks_url": "https://api.github.com/repos/lapty/photoAlbum/forks",
    "keys_url": "https://api.github.com/repos/lapty/photoAlbum/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/photoAlbum/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/photoAlbum/teams",
    "hooks_url": "https://api.github.com/repos/lapty/photoAlbum/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/photoAlbum/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/photoAlbum/events",
    "assignees_url": "https://api.github.com/repos/lapty/photoAlbum/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/photoAlbum/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/photoAlbum/tags",
    "blobs_url": "https://api.github.com/repos/lapty/photoAlbum/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/photoAlbum/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/photoAlbum/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/photoAlbum/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/photoAlbum/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/photoAlbum/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/photoAlbum/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/photoAlbum/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/photoAlbum/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/photoAlbum/subscription",
    "commits_url": "https://api.github.com/repos/lapty/photoAlbum/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/photoAlbum/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/photoAlbum/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/photoAlbum/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/photoAlbum/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/photoAlbum/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/photoAlbum/merges",
    "archive_url": "https://api.github.com/repos/lapty/photoAlbum/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/photoAlbum/downloads",
    "issues_url": "https://api.github.com/repos/lapty/photoAlbum/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/photoAlbum/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/photoAlbum/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/photoAlbum/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/photoAlbum/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/photoAlbum/releases{/id}",
    "created_at": "2014-08-03T03:18:56Z",
    "updated_at": "2014-08-03T03:19:50Z",
    "pushed_at": "2014-08-04T13:29:14Z",
    "git_url": "git://github.com/lapty/photoAlbum.git",
    "ssh_url": "git@github.com:lapty/photoAlbum.git",
    "clone_url": "https://github.com/lapty/photoAlbum.git",
    "svn_url": "https://github.com/lapty/photoAlbum",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22233445,
    "name": "playwithTransitions",
    "full_name": "lapty/playwithTransitions",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/playwithTransitions",
    "description": "Project 4 - July 24",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/playwithTransitions",
    "forks_url": "https://api.github.com/repos/lapty/playwithTransitions/forks",
    "keys_url": "https://api.github.com/repos/lapty/playwithTransitions/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/playwithTransitions/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/playwithTransitions/teams",
    "hooks_url": "https://api.github.com/repos/lapty/playwithTransitions/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/playwithTransitions/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/playwithTransitions/events",
    "assignees_url": "https://api.github.com/repos/lapty/playwithTransitions/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/playwithTransitions/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/playwithTransitions/tags",
    "blobs_url": "https://api.github.com/repos/lapty/playwithTransitions/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/playwithTransitions/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/playwithTransitions/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/playwithTransitions/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/playwithTransitions/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/playwithTransitions/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/playwithTransitions/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/playwithTransitions/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/playwithTransitions/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/playwithTransitions/subscription",
    "commits_url": "https://api.github.com/repos/lapty/playwithTransitions/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/playwithTransitions/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/playwithTransitions/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/playwithTransitions/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/playwithTransitions/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/playwithTransitions/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/playwithTransitions/merges",
    "archive_url": "https://api.github.com/repos/lapty/playwithTransitions/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/playwithTransitions/downloads",
    "issues_url": "https://api.github.com/repos/lapty/playwithTransitions/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/playwithTransitions/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/playwithTransitions/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/playwithTransitions/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/playwithTransitions/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/playwithTransitions/releases{/id}",
    "created_at": "2014-07-24T22:07:48Z",
    "updated_at": "2014-07-25T01:09:22Z",
    "pushed_at": "2014-07-25T01:09:22Z",
    "git_url": "git://github.com/lapty/playwithTransitions.git",
    "ssh_url": "git@github.com:lapty/playwithTransitions.git",
    "clone_url": "https://github.com/lapty/playwithTransitions.git",
    "svn_url": "https://github.com/lapty/playwithTransitions",
    "homepage": null,
    "size": 188,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22628092,
    "name": "profileArrays",
    "full_name": "lapty/profileArrays",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/profileArrays",
    "description": "Github Profile Arrays Project // aug4",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/profileArrays",
    "forks_url": "https://api.github.com/repos/lapty/profileArrays/forks",
    "keys_url": "https://api.github.com/repos/lapty/profileArrays/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/profileArrays/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/profileArrays/teams",
    "hooks_url": "https://api.github.com/repos/lapty/profileArrays/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/profileArrays/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/profileArrays/events",
    "assignees_url": "https://api.github.com/repos/lapty/profileArrays/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/profileArrays/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/profileArrays/tags",
    "blobs_url": "https://api.github.com/repos/lapty/profileArrays/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/profileArrays/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/profileArrays/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/profileArrays/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/profileArrays/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/profileArrays/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/profileArrays/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/profileArrays/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/profileArrays/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/profileArrays/subscription",
    "commits_url": "https://api.github.com/repos/lapty/profileArrays/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/profileArrays/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/profileArrays/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/profileArrays/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/profileArrays/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/profileArrays/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/profileArrays/merges",
    "archive_url": "https://api.github.com/repos/lapty/profileArrays/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/profileArrays/downloads",
    "issues_url": "https://api.github.com/repos/lapty/profileArrays/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/profileArrays/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/profileArrays/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/profileArrays/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/profileArrays/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/profileArrays/releases{/id}",
    "created_at": "2014-08-05T02:57:26Z",
    "updated_at": "2014-08-05T02:58:50Z",
    "pushed_at": "2014-08-05T02:58:49Z",
    "git_url": "git://github.com/lapty/profileArrays.git",
    "ssh_url": "git@github.com:lapty/profileArrays.git",
    "clone_url": "https://github.com/lapty/profileArrays.git",
    "svn_url": "https://github.com/lapty/profileArrays",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22157191,
    "name": "SurfandPaddle",
    "full_name": "lapty/SurfandPaddle",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/SurfandPaddle",
    "description": "Project 3 - Jul 22",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/SurfandPaddle",
    "forks_url": "https://api.github.com/repos/lapty/SurfandPaddle/forks",
    "keys_url": "https://api.github.com/repos/lapty/SurfandPaddle/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/SurfandPaddle/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/SurfandPaddle/teams",
    "hooks_url": "https://api.github.com/repos/lapty/SurfandPaddle/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/SurfandPaddle/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/SurfandPaddle/events",
    "assignees_url": "https://api.github.com/repos/lapty/SurfandPaddle/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/SurfandPaddle/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/SurfandPaddle/tags",
    "blobs_url": "https://api.github.com/repos/lapty/SurfandPaddle/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/SurfandPaddle/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/SurfandPaddle/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/SurfandPaddle/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/SurfandPaddle/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/SurfandPaddle/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/SurfandPaddle/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/SurfandPaddle/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/SurfandPaddle/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/SurfandPaddle/subscription",
    "commits_url": "https://api.github.com/repos/lapty/SurfandPaddle/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/SurfandPaddle/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/SurfandPaddle/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/SurfandPaddle/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/SurfandPaddle/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/SurfandPaddle/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/SurfandPaddle/merges",
    "archive_url": "https://api.github.com/repos/lapty/SurfandPaddle/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/SurfandPaddle/downloads",
    "issues_url": "https://api.github.com/repos/lapty/SurfandPaddle/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/SurfandPaddle/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/SurfandPaddle/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/SurfandPaddle/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/SurfandPaddle/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/SurfandPaddle/releases{/id}",
    "created_at": "2014-07-23T15:32:38Z",
    "updated_at": "2014-07-24T14:31:42Z",
    "pushed_at": "2014-07-29T02:14:34Z",
    "git_url": "git://github.com/lapty/SurfandPaddle.git",
    "ssh_url": "git@github.com:lapty/SurfandPaddle.git",
    "clone_url": "https://github.com/lapty/SurfandPaddle.git",
    "svn_url": "https://github.com/lapty/SurfandPaddle",
    "homepage": "",
    "size": 5076,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22643691,
    "name": "thirtyEvents",
    "full_name": "lapty/thirtyEvents",
    "owner": {
      "login": "lapty",
      "id": 8241367,
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?v=2",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "html_url": "https://github.com/lapty",
      "followers_url": "https://api.github.com/users/lapty/followers",
      "following_url": "https://api.github.com/users/lapty/following{/other_user}",
      "gists_url": "https://api.github.com/users/lapty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lapty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lapty/subscriptions",
      "organizations_url": "https://api.github.com/users/lapty/orgs",
      "repos_url": "https://api.github.com/users/lapty/repos",
      "events_url": "https://api.github.com/users/lapty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lapty/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lapty/thirtyEvents",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/lapty/thirtyEvents",
    "forks_url": "https://api.github.com/repos/lapty/thirtyEvents/forks",
    "keys_url": "https://api.github.com/repos/lapty/thirtyEvents/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lapty/thirtyEvents/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lapty/thirtyEvents/teams",
    "hooks_url": "https://api.github.com/repos/lapty/thirtyEvents/hooks",
    "issue_events_url": "https://api.github.com/repos/lapty/thirtyEvents/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lapty/thirtyEvents/events",
    "assignees_url": "https://api.github.com/repos/lapty/thirtyEvents/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lapty/thirtyEvents/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lapty/thirtyEvents/tags",
    "blobs_url": "https://api.github.com/repos/lapty/thirtyEvents/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lapty/thirtyEvents/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lapty/thirtyEvents/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lapty/thirtyEvents/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lapty/thirtyEvents/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lapty/thirtyEvents/languages",
    "stargazers_url": "https://api.github.com/repos/lapty/thirtyEvents/stargazers",
    "contributors_url": "https://api.github.com/repos/lapty/thirtyEvents/contributors",
    "subscribers_url": "https://api.github.com/repos/lapty/thirtyEvents/subscribers",
    "subscription_url": "https://api.github.com/repos/lapty/thirtyEvents/subscription",
    "commits_url": "https://api.github.com/repos/lapty/thirtyEvents/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lapty/thirtyEvents/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lapty/thirtyEvents/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lapty/thirtyEvents/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lapty/thirtyEvents/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lapty/thirtyEvents/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lapty/thirtyEvents/merges",
    "archive_url": "https://api.github.com/repos/lapty/thirtyEvents/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lapty/thirtyEvents/downloads",
    "issues_url": "https://api.github.com/repos/lapty/thirtyEvents/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lapty/thirtyEvents/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lapty/thirtyEvents/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lapty/thirtyEvents/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lapty/thirtyEvents/labels{/name}",
    "releases_url": "https://api.github.com/repos/lapty/thirtyEvents/releases{/id}",
    "created_at": "2014-08-05T13:04:44Z",
    "updated_at": "2014-08-05T13:05:40Z",
    "pushed_at": "2014-08-05T13:05:40Z",
    "git_url": "git://github.com/lapty/thirtyEvents.git",
    "ssh_url": "git@github.com:lapty/thirtyEvents.git",
    "clone_url": "https://github.com/lapty/thirtyEvents.git",
    "svn_url": "https://github.com/lapty/thirtyEvents",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
]

var eventsArray = [
  {
    "id": "2222964302",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22701250,
      "name": "lapty/manipulatingDomWithConstructors",
      "url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Aug 6 Project",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T23:12:19Z"
  },
  {
    "id": "2222963109",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22701250,
      "name": "lapty/manipulatingDomWithConstructors",
      "url": "https://api.github.com/repos/lapty/manipulatingDomWithConstructors"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "Aug 6 Project",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T23:11:27Z"
  },
  {
    "id": "2221777216",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22682700,
      "name": "lapty/constructorProject",
      "url": "https://api.github.com/repos/lapty/constructorProject"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "playing with constructors",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T13:03:55Z"
  },
  {
    "id": "2221775066",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22682700,
      "name": "lapty/constructorProject",
      "url": "https://api.github.com/repos/lapty/constructorProject"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "playing with constructors",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T13:02:32Z"
  },
  {
    "id": "2219634741",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22643691,
      "name": "lapty/thirtyEvents",
      "url": "https://api.github.com/repos/lapty/thirtyEvents"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T13:05:40Z"
  },
  {
    "id": "2219632167",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22643691,
      "name": "lapty/thirtyEvents",
      "url": "https://api.github.com/repos/lapty/thirtyEvents"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T13:04:44Z"
  },
  {
    "id": "2218917859",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22628092,
      "name": "lapty/profileArrays",
      "url": "https://api.github.com/repos/lapty/profileArrays"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Github Profile Arrays Project // aug4",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T02:58:50Z"
  },
  {
    "id": "2218916681",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22628092,
      "name": "lapty/profileArrays",
      "url": "https://api.github.com/repos/lapty/profileArrays"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "Github Profile Arrays Project // aug4",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T02:57:26Z"
  },
  {
    "id": "2217630060",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 421291708,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "9e1243098cf3c6bdda0b5baefecdbc66ffeddc4d",
      "before": "9f7ae3920c99a99bb04f9277cfc2d4d80049f8c4",
      "commits": [
        {
          "sha": "9e1243098cf3c6bdda0b5baefecdbc66ffeddc4d",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "more concise",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/9e1243098cf3c6bdda0b5baefecdbc66ffeddc4d"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-04T13:29:14Z"
  },
  {
    "id": "2217611949",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 421283615,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "9f7ae3920c99a99bb04f9277cfc2d4d80049f8c4",
      "before": "0d141fdbf4a040768793f012205fa60c79d6a285",
      "commits": [
        {
          "sha": "9f7ae3920c99a99bb04f9277cfc2d4d80049f8c4",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "removed redundancies",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/9f7ae3920c99a99bb04f9277cfc2d4d80049f8c4"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-04T13:18:17Z"
  },
  {
    "id": "2216903723",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 420977827,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "0d141fdbf4a040768793f012205fa60c79d6a285",
      "before": "c5da19ed1c542d09a1c33ce6016489599b256bc2",
      "commits": [
        {
          "sha": "0d141fdbf4a040768793f012205fa60c79d6a285",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "made nav round, looks hip",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/0d141fdbf4a040768793f012205fa60c79d6a285"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-04T01:57:41Z"
  },
  {
    "id": "2216897312",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 420975049,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "c5da19ed1c542d09a1c33ce6016489599b256bc2",
      "before": "9c5893a77387d3b9a49309426da302e9f9d609a5",
      "commits": [
        {
          "sha": "c5da19ed1c542d09a1c33ce6016489599b256bc2",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "added jQuery the correct way",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/c5da19ed1c542d09a1c33ce6016489599b256bc2"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-04T01:47:24Z"
  },
  {
    "id": "2216678001",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 420876034,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "9c5893a77387d3b9a49309426da302e9f9d609a5",
      "before": "1b8dde9d6562bcf45a9cc3c9007e65344679331c",
      "commits": [
        {
          "sha": "9c5893a77387d3b9a49309426da302e9f9d609a5",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "changed colorscheme",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/9c5893a77387d3b9a49309426da302e9f9d609a5"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-03T18:43:03Z"
  },
  {
    "id": "2216349262",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 420726018,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "1b8dde9d6562bcf45a9cc3c9007e65344679331c",
      "before": "e7b0b3fa654776abb2870151e8fed22fb3523578",
      "commits": [
        {
          "sha": "1b8dde9d6562bcf45a9cc3c9007e65344679331c",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "Added cooler box shadow, added border, fixed scaling",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/1b8dde9d6562bcf45a9cc3c9007e65344679331c"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-03T05:05:29Z"
  },
  {
    "id": "2216339119",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "push_id": 420721148,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "e7b0b3fa654776abb2870151e8fed22fb3523578",
      "before": "54aa567152b2f3a3db434e598418c7e054a91fcc",
      "commits": [
        {
          "sha": "e7b0b3fa654776abb2870151e8fed22fb3523578",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "Added more images, added striped background image to nav, made album title reset images",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/photoAlbum/commits/e7b0b3fa654776abb2870151e8fed22fb3523578"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-03T04:31:03Z"
  },
  {
    "id": "2216315544",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Basic jQuery photo album project",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-03T03:19:50Z"
  },
  {
    "id": "2216315256",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22565887,
      "name": "lapty/photoAlbum",
      "url": "https://api.github.com/repos/lapty/photoAlbum"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "Basic jQuery photo album project",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-03T03:18:57Z"
  },
  {
    "id": "2211943781",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22455349,
      "name": "lapty/basicJavascript",
      "url": "https://api.github.com/repos/lapty/basicJavascript"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-31T04:13:52Z"
  },
  {
    "id": "2211919683",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22455349,
      "name": "lapty/basicJavascript",
      "url": "https://api.github.com/repos/lapty/basicJavascript"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-31T03:44:08Z"
  },
  {
    "id": "2209723626",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22399039,
      "name": "lapty/letsEat",
      "url": "https://api.github.com/repos/lapty/letsEat"
    },
    "payload": {
      "push_id": 417810815,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "73245eb1262116f9854e95bca666594ba5247c03",
      "before": "261613bd9d16ee805f8544f76651f54c094ee029",
      "commits": [
        {
          "sha": "73245eb1262116f9854e95bca666594ba5247c03",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "Making it purdier",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/letsEat/commits/73245eb1262116f9854e95bca666594ba5247c03"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-30T02:44:59Z"
  },
  {
    "id": "2209492159",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22399039,
      "name": "lapty/letsEat",
      "url": "https://api.github.com/repos/lapty/letsEat"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "layout project, modified for responsive",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-29T23:04:03Z"
  },
  {
    "id": "2209490076",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22399039,
      "name": "lapty/letsEat",
      "url": "https://api.github.com/repos/lapty/letsEat"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "layout project, modified for responsive",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-29T23:02:31Z"
  },
  {
    "id": "2207578102",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22157191,
      "name": "lapty/SurfandPaddle",
      "url": "https://api.github.com/repos/lapty/SurfandPaddle"
    },
    "payload": {
      "push_id": 416888340,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "d2f42fe34d2e8fa5d0ffe7d7b40324974d035432",
      "before": "1424694db4890ac82cfddf08e4bcd59f499b901c",
      "commits": [
        {
          "sha": "d2f42fe34d2e8fa5d0ffe7d7b40324974d035432",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "cleaned responsive a little",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/SurfandPaddle/commits/d2f42fe34d2e8fa5d0ffe7d7b40324974d035432"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-29T02:14:34Z"
  },
  {
    "id": "2207425368",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22157191,
      "name": "lapty/SurfandPaddle",
      "url": "https://api.github.com/repos/lapty/SurfandPaddle"
    },
    "payload": {
      "push_id": 416825697,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "1424694db4890ac82cfddf08e4bcd59f499b901c",
      "before": "819c85c79d57c316ce5afe46dd8c9598c0006b11",
      "commits": [
        {
          "sha": "1424694db4890ac82cfddf08e4bcd59f499b901c",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "Trying to add responsive",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/SurfandPaddle/commits/1424694db4890ac82cfddf08e4bcd59f499b901c"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-28T23:46:26Z"
  },
  {
    "id": "2205309544",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22312443,
      "name": "lapty/climbOn",
      "url": "https://api.github.com/repos/lapty/climbOn"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Playing with layout + design. <3climbing",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-27T14:17:32Z"
  },
  {
    "id": "2205308435",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22312443,
      "name": "lapty/climbOn",
      "url": "https://api.github.com/repos/lapty/climbOn"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "Playing with layout + design. <3climbing",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-27T14:14:49Z"
  },
  {
    "id": "2204839429",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22157191,
      "name": "lapty/SurfandPaddle",
      "url": "https://api.github.com/repos/lapty/SurfandPaddle"
    },
    "payload": {
      "push_id": 415624625,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "819c85c79d57c316ce5afe46dd8c9598c0006b11",
      "before": "2fcd6f92506781da2fae0e189df1d29ec8815113",
      "commits": [
        {
          "sha": "819c85c79d57c316ce5afe46dd8c9598c0006b11",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "text on bottonav, need title fix",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/SurfandPaddle/commits/819c85c79d57c316ce5afe46dd8c9598c0006b11"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-26T16:28:30Z"
  },
  {
    "id": "2204305832",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22273087,
      "name": "lapty/charlesqnguyen",
      "url": "https://api.github.com/repos/lapty/charlesqnguyen"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-25T22:40:10Z"
  },
  {
    "id": "2203499506",
    "type": "PushEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22157191,
      "name": "lapty/SurfandPaddle",
      "url": "https://api.github.com/repos/lapty/SurfandPaddle"
    },
    "payload": {
      "push_id": 415018310,
      "size": 2,
      "distinct_size": 2,
      "ref": "refs/heads/master",
      "head": "2fcd6f92506781da2fae0e189df1d29ec8815113",
      "before": "f1b4b63be6e5aa154e44546147efd234a7fd8a2b",
      "commits": [
        {
          "sha": "fd706dbe0dfc051d63dd3ba86d12aabe4fdf98c6",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "Fixed top, added surfbanner",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/SurfandPaddle/commits/fd706dbe0dfc051d63dd3ba86d12aabe4fdf98c6"
        },
        {
          "sha": "2fcd6f92506781da2fae0e189df1d29ec8815113",
          "author": {
            "email": "charles.qh.nguyen@gmail.com",
            "name": "lapty"
          },
          "message": "header bleeds to edges",
          "distinct": true,
          "url": "https://api.github.com/repos/lapty/SurfandPaddle/commits/2fcd6f92506781da2fae0e189df1d29ec8815113"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-25T14:25:43Z"
  },
  {
    "id": "2202652743",
    "type": "CreateEvent",
    "actor": {
      "id": 8241367,
      "login": "lapty",
      "gravatar_id": "44e70bdb10f0a876fcabd3c805f497a3",
      "url": "https://api.github.com/users/lapty",
      "avatar_url": "https://avatars.githubusercontent.com/u/8241367?"
    },
    "repo": {
      "id": 22233445,
      "name": "lapty/playwithTransitions",
      "url": "https://api.github.com/repos/lapty/playwithTransitions"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "Project 4 - July 24",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-25T01:09:22Z"
  }
]
